### PR TITLE
RPM packaging for testing

### PR DESCRIPTION
**Pull request by brianjmurrell**
Until all of our work is pushed upstream and available to us from either the official mpich
upstream or better yet, from the distribution.

### CODE REVIEW

**Comment by mchaarawi** [comment]
i really don't want to merge this into my branch.. i would keep this in a separate branch.

**Comment by brianjmurrell** [comment]
> i really don't want to merge this into my branch.. i would keep this in a separate branch.

How do the changes that get added to this branch get on to the branch where RPMs are built every time there is a change on this branch?

**Comment by mchaarawi** [comment]
> > i really don't want to merge this into my branch.. i would keep this in a separate branch.
> 
> How do the changes that get added to this branch get on to the branch where RPMs are built every time there is a change on this branch?

well how do you expect this would work when this is merged upstream and the branch is removed?

**Comment by brianjmurrell** [comment]
> well how do you expect this would work when this is merged upstream and the branch is removed?

At that time, we will have an official upstream release that we can build RPMs against, like we do for many other projects.  But since there are no releases being made anywhere that have the DAOS changes in them, we cannot do this at this time.

**Comment by mchaarawi** [comment]
> > well how do you expect this would work when this is merged upstream and the branch is removed?
> 
> At that time, we will have an official upstream release that we can build RPMs against, like we do for many other projects. But since there are no releases being made anywhere that have the DAOS changes in them, we cannot do this at this time.

IMO those changes should be made in a different repo rather than this one.

**Comment by brianjmurrell** [comment]
> IMO those changes should be made in a different repo rather than this one.

Once we have an MPICH release that we can build from, we can do this a different repo.  But we don't have that yet.  So we have nothing except this repo to build against.

**Comment by mchaarawi** [comment]
> > > well how do you expect this would work when this is merged upstream and the branch is removed?
> > 
> > 
> > At that time, we will have an official upstream release that we can build RPMs against, like we do for many other projects. But since there are no releases being made anywhere that have the DAOS changes in them, we cannot do this at this time.
> 
> IMO those changes should be made in a different repo rather than this one.



> > IMO those changes should be made in a different repo rather than this one.
> 
> Once we have an MPICH release that we can build from, we can do this a different repo. But we don't have that yet. So we have nothing except this repo to build against.

i guess im not understanding what the difference is between having an mpich release vs treating this branch as the release. anyway, if this is temporary, then we can keep it in a separate branch and sync changes between the branches. development on this repo is not very active.

**Comment by brianjmurrell** [comment]
Having it on a separate branch that gets the daos_adio branch merged into it every time there is an update to the daos_adio branch is fine.  It achieves the same goal.  It just becomes another step for you in maintaining this repo until we have an upstream release with the required DAOS changes in it so that we can move RPM building to a more traditional process where upstream releases can be consumed.

As an aside, do you have any timeline for when an upstream release will be made with our DAOS changes in it?  I think you said you have submitted a PR for them, yes?  But if it's to master, I guess it will have to wait for another major or minor release before we see them.

**Comment by mchaarawi** [comment]
> Having it on a separate branch that gets the daos_adio branch merged into it every time there is an update to the daos_adio branch is fine. It achieves the same goal. It just becomes another step for you in maintaining this repo until we have an upstream release with the required DAOS changes in it so that we can move RPM building to a more traditional process where upstream releases can be consumed.
> 
> As an aside, do you have any timeline for when an upstream release will be made with our DAOS changes in it? I think you said you have submitted a PR for them, yes? But if it's to master, I guess it will have to wait for another major or minor release before we see them.

creating a PR / update for the changes should be minimal work since it's not much changes, just some updates when the DAOS API changes.
As for the merge upstream, Kevin is going to ping the MPICh maintainers again to review the PR and get it moving.. i don't have a timeline.
It will be to master, and then im guessing to the next release after it lands.

**Comment by brianjmurrell** [comment]
> creating a PR / update for the changes should be minimal work since it's not much changes, just some updates when the DAOS API changes.

I'm thinking this has to do with my proposal that the RPM building branch needs to have daos_adio merged to it every time daos_adio is updates, but I'm not following your proposal for a PR / update.

I envisioned the process to be a simple

```
git checkout RPM
git merge daos_adio
git push origin RPM
```

Are you envisioning something different?

**Comment by mchaarawi** [comment]
> > creating a PR / update for the changes should be minimal work since it's not much changes, just some updates when the DAOS API changes.
> 
> I'm thinking this has to do with my proposal that the RPM building branch needs to have daos_adio merged to it every time daos_adio is updates, but I'm not following your proposal for a PR / update.
> 
> I envisioned the process to be a simple
> 
> ```
> git checkout RPM
> git merge daos_adio
> git push origin RPM
> ```
> 
> Are you envisioning something different?

no, i just meant you can do the same by creating a PR from daos_adio to RPM and merge it anytime a patch is landed on daos_adio. so same process that can be done from the github UI.

**Comment by brianjmurrell** [comment]
> no, i just meant you can do the same by creating a PR from daos_adio to RPM and merge it anytime a patch is landed on daos_adio. so same process that can be done from the github UI.

@mchaarawi You are the only one that knows when something new lands to mpich/daos_adio.  I am trying to come up with a process that makes the production of the product of that change as automatic and lightweight as possible within the current workflow.

**Comment by brianjmurrell** [comment]
@mchaarawi Additionally, when we add regression testing to this repo in the form of testing it's RPM with the daos stack of RPMs, as a gate to landing changes in this repo, how do you envision this happening if the RPM is not being built (and tested) in a PR based on the branch the changes are going to be landed to?

I.e. The CI build and test process for this repo is to build the PR into an RPM and install it along with the daos master RPMs and run tests.  If the tests pass, the PR is good and can be landed to the daos_adio branch.  But that only works if we can build the RPM from target branch.

But even CI testing aside, can you describe what you think the workflow for producing RPMs is for a PR that you have based on daos_adio branch, as I'm not really seeing how you envision that working without adding the RPM building code to the repo so that the RPM is built when you land the change.  Step by step from the point where you have pushed your patch to the PR please so that I can implement that as this is blocking getting IOR testing in CI, which is my top priority at the moment.

**Comment by mchaarawi** [comment]
the workflow on this branch has always been me pushing directly. I'm the only one contributing to this branch fwiw. As i mentioned, i can update whatever branch you have with your changes when i push to this branch, which isn't frequent, and you can do the RPM testing there.
And again, development on this branch is done, other than updates that will be done when the DAOS API changes. I want to keep this branch with only PRs that will make it upstream.

**Comment by brianjmurrell** [comment]
In that case, then we can just push this directly to a branch.  How about `daos_adio-rpm`?

**Comment by mchaarawi** [comment]
> In that case, then we can just push this directly to a branch. How about `daos_adio-rpm`?

that's fine.. the RPM branch you pushed this from should work too?

**Comment by brianjmurrell** [comment]
> that's fine.. the RPM branch you pushed this from should work too?

I'll delete that one as I've already update the ior-hpc repo to use daos_adio-rpm and I like that it makes it clear what this is the RPM build of.

**Pull request closed without merging**
